### ISSUE TITLE
Updating from 1.1.3 to 1.1.9 deleted all items from the brewery drawers

### ISSUE THREAD

**Issue by twoface99** [satisfyu/Let-s-Do-Hub#124]
### Minecraft Version

1.20.1

### Mod

Brewery

### Mod Version

1.1.9

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

After updating the mod from version 1.1.3 to 1.1.9 all drawers on my server are now empty. 

### Steps to Reproduce

1. Use version 1.1.3
2. Place and fill drawers with items
3. Update mod to 1.1.9
4. Open drawers to see items gone

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
The issue lies with some refactors in the doAPI - unfortunately, there's nothing that can be done to undo this. I'm sorry about your lost items.

If you have a backup, you could restore it and remove the items from the drawer beforehand. It's a bit of work but unfortunately the only solution.

As a positive side effect, you now have two more rows of space! :)
