### ISSUE TITLE
Crash after updating to 1.4.29 from 1.4.28 with BClib being present

### ISSUE THREAD

**Issue by totrider** [satisfyu/Let-s-Do-Hub#377]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.29

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

The latest Vinery update causes Minecraft to crash before it loads into the main menu.

I see a lot of reported issue on BCLib repo that have similar looking logs related to rg.betterx.bclib.client.models.CustomModelBakery.addItemModel - but as far as I could see, there were none of them running the latest Vinery version which is the only one causing a problem to me at least.

Already had to spend ~2 hours to find out this mod being updated was causing my problem, so pardon me for not doing a minimal instance test ^^'

### Steps to Reproduce

Update mod and launch.

This modpack version works as is: https://modrinth.com/modpack/dragon-claw-persistent/version/2.8.2 -> update Vinery, and it will crash before reaching the main menu.

### Logs

Full log: https://pastebin.com/Y3D2EDam

Crash log: https://pastebin.com/SMG8803p

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Hi there!

As mentioned in the latest changelog, Vinery 1.4.29 is currently not compatible due to some internal refactoring. This is why it is marked as incompatible for now.

I’m planning to upload the updated version later today or tomorrow. However, the required changes turned out to be more complex than I initially expected.

Thank you for your patience!
