### ISSUE TITLE
Flower Seeds for all the flowers....MMMM

### ISSUE THREAD

**Issue by jimmytrouser** [satisfyu/Let-s-Do-Hub#89]
### Mod Name and Version

Let's Do Blooming Nature 1.20.1

### Suggestion Details

Three options here:

1. Would love the have flower seeds so I can grow all the flowers.
2. Bonemeal flowers, so I can make more.
3. Flower trader (bit like farming for blockheads trader or Bountiful questing board); this could be incorporated with all the 'Let's do mods' so I can bake cakes or make wine to trade in for seeds, for example - sounds cool eh.

### Expected Benefits

All the flowers for builders and cosy players, and anyone really.

### Potential Drawbacks

More coding??

### Check for Similar Suggestions

- [X] Yes, I've looked for similar ideas.

**Comment by satisfyu** [comment]
A bounty board for quests is coming with one of the upcoming new mods. Players will be able to add new tasks there easily – however, i don't plan to include flowers as rewards.

In my opinion, flower seeds don't really fit the game design – I also think it's important for players to actively explore rather than farming everything in their own four chunks.
