### ISSUE TITLE
Meadow's pine hanging sign loses the pine texture when Amendments is installed.

### ISSUE THREAD

**Issue by Robynstar** [satisfyu/Let-s-Do-Hub#99]
### Minecraft Version

1.20.1

### Mod

Meadow

### Mod Version

1.3.17

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

When installed with Amendments, the pine hanging signs have their texture replaced with oak.
This is being discussed over on an Amendments issue (https://github.com/MehVahdJukaar/amendments/issues/52) but I thought I would at least raise it over here seeing as hanging signs from e.g. Quark do not have the same issue.
Something about it not having been added to the vanilla texture map?

### Steps to Reproduce

Install Meadow
Install [Amendments](https://www.curseforge.com/minecraft/mc-mods/amendments/files/5467925)
Place a pine hanging sign
Be surprised it looks like an oak one

**Or alternatively**
Install Meadow
Place a pine hanging sign
Install Amendments
Wonder where your pine sign went

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
We're using the TeraformerMC API for registering signs, boats, etc.. 

I'll dig into this a bit deeper as soon as i have time.

**Comment by satisfyu** [comment]
Related to the doAPI. 

Since the API is developed and maintained by Cristelknight you would have to report it there and hope he will be back anytime soon to fix it. 
https://github.com/Team-Let-s-Do/DoAPI/issues

Im currently working on removing it completely because of these kind of errors / as well as difficulties in maintenance and updating it myself.
